{
 "title": "Wikipedia Spider",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Sites Visited",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(sites_visited_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Links Found",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(page_title) (rate(links_found_total[$__rate_interval])) > 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Visit Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(error) (rate(visit_error_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}